name: ml-cicd-marketing-campaign
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  trigger-demo:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Labeling Data
      run: echo "Labeling"

    - name: 2. Compose Data
      run: echo "Composing Data"

    - name: 3. Unit Test
      run: echo "unit test"

    - name: 3. Smoke Test
      run: echo "smoke test"
    
    - name: 1. Hyperparameter Tuning
      run: echo "hyperparameter tuning"

    - name: 1. Train
      run: echo "train"

    - name: 1. Evaluate
      run: echo "evaluate"

    - name: 1. Deploy
      run: echo "deploy"