name: ml-cicd

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  ml-cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@main  
    
    - name: Install Conda environment
      run: |
        conda env create --name ml-cicd --file test/conda-environment.yaml
        conda init bash
        cat /home/runner/.bashrc
      shell: bash

    - name: Activate Conda environment
      run: |
        conda init zsh
        source /usr/share/miniconda/bin/activate
        conda activate ml-cicd 
      shell: bash

    - name: Test env
      shell: python
      run: |
        import pandas as pd
        import numpy as np
        from sklearn.compose import ColumnTransformer
        from xgboost import XGBClassifier
        from lightgbm import LGBMClassifier
        from catboost import CatBoostClassifier
        import wandb
        import seaborn as sns
        import matplotlib.pyplot as plt
        print("All Done!")
    
    - name: 1. Labeling Data
      run: echo "Labeling"

    - name: 2. Compose Data
      run: echo "Composing Data"

    - name: 3. Unit Test
      run: echo "unit test"

    - name: 3. Smoke Test
      run: echo "smoke test"
    
    - name: 4. Hyperparameter Tuning
      run: echo "hyperparameter tuning"

    - name: 5. Train
      run: echo "train"

    - name: 6. Evaluate
      run: echo "evaluate"

    - name: 7. Deploy
      run: echo "deploy"
