name: ml-cicd

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  ml-cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@main  
    
    - name: Install Conda environment
      run: |
        conda env create --name ml-cicd --file test/conda-environment.yaml
        conda init bash
        source /usr/share/miniconda/bin/activate
        cat /home/runner/.bashrc
      shell: bash

    - name: Test Conda environment
      run: |
        conda init zsh
        source /usr/share/miniconda/bin/activate
        conda activate ml-cicd 
        conda run -n ml-cicd python test/testlib.py
      shell: bash
    
    - name: 1. Labeling Data
      run: echo "Labeling"

    - name: 2. Compose Data
      run: echo "Composing Data"

    - name: 2. Generate EDA Report
      run: echo "Generate wandb report"

    - name: 3. Unit Test
      run: |
        conda run -n ml-cicd python test/test_add_features.py
      shell: bash

      

    - name: 3. Smoke Test
      run: |
        conda run -n ml-cicd python smoke_test_train/train.py
      shell: bash
    
    - name: 4. Hyperparameter Tuning
      run: |
        conda run -n ml-cicd python hyperparameters_tuning/tune_hyperparameter.py
      shell: bash

    - name: 5. Train
      run: |
        conda run -n ml-cicd python train/train.py
      shell: bash

    - name: 6. Evaluate
      run: echo "evaluate"

    - name: 7. Deploy
      run: echo "deploy"
