name: ml-cicd

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  ml-cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@main  
    
    - name: Install Conda environment
      run: echo "Installing Conda environment"
    
    - name: 1. Labeling Data
      run: echo "Labeling"

    - name: 2. Compose Data
      run: echo "Composing Data"

    - name: 3. Unit Test
      run: echo "unit test"

    - name: 3. Smoke Test
      run: echo "smoke test"
    
    - name: 4. Hyperparameter Tuning
      run: echo "hyperparameter tuning"

    - name: 5. Train
      run: echo "train"

    - name: 6. Evaluate
      run: echo "evaluate"

    - name: 7. Deploy
      run: echo "deploy"
