name: ml-cicd

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  ml-cicd:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@main  
    
    - name: Install Conda environment
      run: |
        conda env create --name ml-cicd --file test/conda-environment.yaml
      shell: bash

    - name: Test Conda environment
      run: |
        conda run -n ml-cicd python test/testlib.py
      shell: bash

    - name: 1. Generate EDA Report
      run: |
        conda run -n ml-cicd python generate_eda_report/report.py
      shell: bash

    - name: 2a. Unit Test
      run: |
        conda run -n ml-cicd python test/test_add_features.py
      shell: bash

    - name: 2b. Smoke Test
      run: |
        conda run -n ml-cicd python smoke_test_train/train.py
      shell: bash
    
    - name: 3. Hyperparameter Tuning
      run: |
        conda run -n ml-cicd python hyperparameters_tuning/tune_hyperparameter.py
      shell: bash

    - name: 4. Train
      run: |
        conda run -n ml-cicd python train/train.py
      shell: bash

    - name: 5. Deploy
      run: |
        conda run -n ml-cicd python inference/inference.py
      shell: bash

    - name: 6. Test API
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"age": 32, "job": "management", "marital": "married", "education": "tertiary", "default": "no", "balance": 1500, "housing": "no", "loan": "no", "contact": "cellular", "day": 28, "month": "jan", "duration": 458, "campaign": 2, "pdays": -1, "previous": 0, "poutcome": "unknown", "is_elderly": 1, "has_housing_loan": 0, "is_married": 1, "has_previous_contact": 1, "is_tertiary_educated": 1, "is_admin_job": 0, "has_default": 0, "is_month_may": 0, "is_loan": 0, "campaign_greater_than_1": 1}' http://127.0.0.1:5000/predict
      shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}